---
title: "SLR Analysis for Modeling AoA (sweep-dataset)"
author: "Mohammad Hosseini (<mohammadhosseini@vt.edu>)"
subtitle: VT-Roller Rig Data Analytics Project (March 3, 2020)
output:
  html_document: default
---

***
> **Analysis**

<br>

### 1. Regressing Longitudinal Force on AoA

```{r SLRs.long}
load("longForce_AoA_100.rda")
data <- longForce_AoA_100

## Training and testing data sets
n <- nrow(data)
size <- floor(n*0.7)
train.ind <- sample(n, size, replace=FALSE)
train <- data[train.ind,]
test <- data[-train.ind,]

# Running linear regressions
lm.AoA <- lm(train$longitudinal.force ~ train$AoA)

# Plotting the regression lines
plot(train$AoA, train$longitudinal.force, xlab="AoA",
     ylab="Longitudinal Force", col=1, pch=20, main=""); abline(lm.AoA, col="indianred1", lwd=2)

summary(lm.AoA)
```

<br>

#### 1.1 Checking SLR Assumptions

```{r assumptions.check}
par(mfrow = c(2, 2), mai=c(.7,.7,.2,.2))
plot(train$AoA, train$longitudinal.force, xlab="AoA",
     ylab="Longitudinal Force", col=1, pch=20, main=""); abline(lm.AoA, col="indianred1", lwd=2)
## AoA
plot(lm.AoA$fitted, rstudent(lm.AoA),xlab="Fitted values", ylab="Studentized Residuals",
     col=1, main=""); abline(h=0, col=8, lty=2)
qqnorm(rstudent(lm.AoA), pch=20, col="indianred1", main=""); abline(a=0, b=1, lty=2)
hist(rstudent(lm.AoA),freq=FALSE, col="indianred1", xlab="Studentized Residuals", main="")
```

<br>

### 2. AoA with a Polynomial Kernel

```{r, message=FALSE, warning=FALSE}
# Running linear regression
train$AoA2 <- train$AoA^2
lm.AoA2 <- lm(longitudinal.force ~ AoA + AoA2, data=train)

# Plotting the regression lines
plot(train$AoA, train$longitudinal.force, xlab="AoA", ylab="Longitudinal Force",
     col=1, pch=20, main="")
xgrid <- seq(-1,1,length=100)
ygrid <- lm.AoA2$coef[1] + lm.AoA2$coef[2]*xgrid + lm.AoA2$coef[3]*xgrid^2
lines(xgrid, ygrid, col="indianred1", lwd=2)

library(sjPlot, quietly = TRUE)
summary(lm.AoA2)
tab_model(lm.AoA2)
```

<br>

#### 2.1 Checking SLR Assumptions

```{r assumptions.check2}
par(mfrow = c(2, 2), mai=c(.7,.7,.2,.2))
plot(train$AoA, train$longitudinal.force, xlab="AoA", ylab="Longitudinal Force",
     col=1, pch=20, main="Polynomial Kernel")
xgrid <- seq(-1,1,length=100)
ygrid <- lm.AoA2$coef[1] + lm.AoA2$coef[2]*xgrid + lm.AoA2$coef[3]*xgrid^2
lines(xgrid, ygrid, col="indianred1", lwd=2)
## AoA
plot(lm.AoA2$fitted, rstudent(lm.AoA2),xlab="Fitted values", ylab="Studentized Residuals",
     col=1, main=""); abline(h=0, col=8, lty=2)
qqnorm(rstudent(lm.AoA2), pch=20, col="indianred1", main=""); abline(a=0, b=1, lty=2)
hist(rstudent(lm.AoA2),freq=FALSE, col="indianred1", xlab="Studentized Residuals", main="")
```
<br>

### 3. AoA, Only Quadratic Term
```{r, message=FALSE, warning=FALSE}
# Running linear regression
lm.AoA3 <- lm(longitudinal.force ~ AoA2, data=train)

# Plotting the regression lines
plot(train$AoA, train$longitudinal.force, xlab="AoA", ylab="Longitudinal Force",
     col=1, pch=20, main="")
xgrid <- seq(-1,1,length=100)
ygrid <- lm.AoA3$coef[1] + lm.AoA3$coef[2]*xgrid^2
lines(xgrid, ygrid, col="indianred1", lwd=2)

summary(lm.AoA3)
tab_model(lm.AoA3)
```

<br>

#### 3.1 Checking SLR Assumptions

```{r assumptions.check3}
par(mfrow = c(2, 2), mai=c(.7,.7,.2,.2))
plot(train$AoA, train$longitudinal.force, xlab="AoA", ylab="Longitudinal Force",
     col=1, pch=20, main="AoA-Squared")
xgrid <- seq(-1,1,length=100)
ygrid <- lm.AoA3$coef[1] + lm.AoA3$coef[2]*xgrid^2
lines(xgrid, ygrid, col="indianred1", lwd=2)
## AoA
plot(lm.AoA3$fitted, rstudent(lm.AoA3),xlab="Fitted values", ylab="Studentized Residuals",
     col=1, main=""); abline(h=0, col=8, lty=2)
qqnorm(rstudent(lm.AoA3), pch=20, col="indianred1", main=""); abline(a=0, b=1, lty=2); hist(rstudent(lm.AoA3),freq=FALSE, col="indianred1", xlab="Studentized Residuals", main="")
```

<br>

### 4. Comparing Models via ANOVA

```{r, message=FALSE, warning=FALSE}
anova(lm.AoA2,lm.AoA3)
```

***
